### ISSUE TITLE
Frontend flask update

### ISSUE THREAD

**Issue by PeckBray** [PeckBray/CS-3321-Team-3-Project#7]
Get the front end ready to communicate with Flask once the code is hosted.

- get links set up to properly import and export data
- be able to accept multiple queries without refreshing

**Comment by nielrya4** [comment]
#8 solves this in the index.html file

**Comment by nielrya4** [comment]
Accidentally closed this, lol I'm new to git. The issue will be fixed once #8 is pulled and merged with main

**Comment by nielrya4** [comment]
Solved by #8
